<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tanzpartnersuche"
 *
 * Auto generated by Extension Builder 2021-09-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Tanzpartnersuche',
    'description' => 'A typo3 extension for our dancing club, used to find a dancing partner.',
    'category' => 'plugin',
    'author' => 'Peter-Benedikt von Niebelschütz, Martin Arend',
    'author_email' => 'ias@gsc-muenchen.de, ias@gsc-muenchen.de',
    'state' => 'alpha',
    'clearCacheOnLoad' => 0,
    'version' => '0.3',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
