<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tanzpartnersuche"
 *
 * Auto generated by Extension Builder 2021-08-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Tanzpartnersuche',
    'description' => 'This Typo3 extension adds functionality that allows people to use for finding a new dancing partner.',
    'category' => 'plugin',
    'author' => 'Peter von Niebelschütz, Martin Arend',
    'author_email' => 'ias@gsc-muenchen.de, ias@gsc-muenchen.de',
    'state' => 'alpha',
    'clearCacheOnLoad' => 0,
    'version' => '0.2',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
